package com.example.impulsepurchaserecoverykit.viewmodel

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.example.impulsepurchaserecoverykit.AnthropicApiClient
import com.example.impulsepurchaserecoverykit.BuildConfig
import com.example.impulsepurchaserecoverykit.database.AppDatabase
import com.example.impulsepurchaserecoverykit.database.ReceiptRepository
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch


/**
 * ChatMessage represents a single message in the KIRA conversation.
 *
 *   @property role The sender of the message — either "user" for messages sent
 *                  by the user or "assistant" for responses generated by KIRA
 *   @property content The text content of the message
 *   @property isLoading Indicates whether this message is a temporary loading
 *                       placeholder — used to show a typing indicator whilst
 *                       the API response is being generated
 */
data class ChatMessage(
    val role: String,   // "user" or "assistant"
    val content: String,
    val isLoading: Boolean = false
)

/**
 * SuggestionBotViewModel manages all state and business logic for the KIRA
 * conversational assistant feature of the IPRK.
 *
 * This ViewModel is responsible for:
 *   - Loading the user's real spending data from the database on initialisation
 *   - Generating KIRA's personalised greeting message using live database values
 *   - Managing the conversation message history as a reactive StateFlow
 *   - Sending user messages to the Anthropic Claude API via AnthropicApiClient
 *   - Building a system containing the user's actual spending data to enable
 *     genuinely personalised responses from the Claude model
 *   - Managing loading and error states for the chat interface
 */
class SuggestionBotViewModel(application: Application) : AndroidViewModel(application) {

    /**
     * The repository provides access to all receipt data from the Room database.
     * Used to retrieve spending statistics for the system prompt and greeting.
     */
    private val repository = ReceiptRepository(AppDatabase.getDatabase(application))

    /**
     * The internal mutable state holding the current conversation message history.
     * Initially empty until the greeting message is loaded in the init block.
     */
    private val _messages = MutableStateFlow<List<ChatMessage>>(emptyList())
    /**
     * The publicly exposed read-only StateFlow of the conversation message history.
     * It is observed by the SuggestionBotScreen to render the chat interface reactively.
     * And emits a new list whenever a message is added to the conversation.
     */
    val messages: StateFlow<List<ChatMessage>> = _messages

    /**
     * The internal mutable state indicating whether an API request is in progress.
     * It sets to true when a message is sent and false when the response is received.
     */
    private val _isLoading = MutableStateFlow(false)
    /**
     * The publicly exposed read-only StateFlow of the loading state.
     * It is observed by the SuggestionBotScreen to display the typing indicator
     * and disable the send button whilst a response is being generated.
     */
    val isLoading: StateFlow<Boolean> = _isLoading

    /**
     * The internal mutable state holding the current error message if any.
     * Null when no error has occurred. Set when an API call fails.
     */
    private val _error = MutableStateFlow<String?>(null)

    /**
     * The publicly exposed read-only StateFlow of the current error message.
     * Observed by the SuggestionBotScreen to display error snackbars.
     * Null when no error has occurred.
     */
    val error: StateFlow<String?> = _error

    /**
     * The publicly exposed read-only StateFlow of the current error message.
     * Observed by the SuggestionBotScreen to display error snackbars.
     * Null when no error has occurred.
     * If no receipts have been logged yet, a welcome message encouraging the
     * user to scan their first receipt is displayed instead of the statistics.
     *
     * The greeting is added as the first message in the conversation history,
     * appearing as a KIRA assistant message in the chat interface.
     */
    init{
        // Load greeting with real data as soon as ViewModel is created
        viewModelScope.launch {
            val receipts = repository.getAllReceipts().first()
            val totalSpend = receipts.sumOf { it.totalAmount ?: 0.0 }
            val receiptCount = receipts.size
            val ratedReceipts = receipts.filter { it.regretScore != null }
            val avgRegret = if (ratedReceipts.isNotEmpty())
                ratedReceipts.mapNotNull { it.regretScore }.average()
            else null
            val highRegretCount = receipts.count { (it.regretScore ?: 0) >= 8 }
            val topStore = receipts
                .groupBy { it.storeName ?: "Unknown" }
                .entries
                .sortedByDescending { it.value.size }
                .firstOrNull()?.key ?: "unknown"

            val greeting = if (receiptCount == 0) {
                "Hi! I'm KIRA, your spending coach 🤖 You haven't logged any receipts yet — " +
                        "scan your first one and come back to me for personalised advice!"
            } else {
                "Hi! I'm KIRA, your spending coach 🤖 Here's what I can see:\n\n" +
                        "📊 $receiptCount receipts logged\n" +
                        "💰 £${String.format("%.2f", totalSpend)} total spend\n" +
                        "😬 ${avgRegret?.let { String.format("%.1f", it) } ?: "No ratings yet"} / 10 avg regret\n" +
                        "⚠️ $highRegretCount high-regret purchases (8+)\n" +
                        "🏪 Most visited: $topStore\n\n" +
                        "What would you like help with? Ask me about a purchase you're considering, " +
                        "or I can dig deeper into your patterns."
            }

            _messages.value = listOf(
                ChatMessage(role = "assistant", content = greeting)
            )
        }
    }

    /**
     * Sends a user message to KIRA and adds the generated response to the
     * conversation history.
     * 1. Adds the user message immediately to the conversation history
     *    so the interface feels responsive before the API responds
     *  2. Sets the loading state to true to display the typing indicator
     *  3. Builds a personalised system prompt using the user's live database data
     *  4. Passes the full conversation history to the AnthropicApiClient
     *  5. Adds KIRA's response to the conversation history on success
     *  6. Sets an error message on failure and resets the loading state
     */
    fun sendMessage(userInput: String) {
        if (userInput.isBlank()) return

        // Add user message immediately
        val updatedMessages = _messages.value + ChatMessage(role = "user", content = userInput)
        _messages.value = updatedMessages
        _isLoading.value = true
        _error.value = null

        viewModelScope.launch {
            try {
                val systemPrompt = buildSystemPrompt()

                // Build message history for API (exclude loading messages)
                val apiMessages = _messages.value
                    .filter { !it.isLoading }
                    .map { it.role to it.content }

                val response = AnthropicApiClient.sendMessage(
                    apiKey = BuildConfig.ANTHROPIC_API_KEY,
                    systemPrompt = systemPrompt,
                    messages = apiMessages
                )

                _messages.value = _messages.value + ChatMessage(
                    role = "assistant",
                    content = response
                )

            } catch (e: Exception) {
                _error.value = "Couldn't reach the bot. Check your connection and try again."
                android.util.Log.e("BOT_DEBUG", "Full error", e)
            } finally {
                _isLoading.value = false
            }
        }
    }

    /**
     * Builds the system prompt sent to the Claude API with every message.
     *
     * The system injects the user's real spending data directly into the prompt
     * so that every response is personalised to the individual user rather than
     * being generic financial advice.
     */
    private suspend fun buildSystemPrompt(): String {
        // Pull real user data from the database to personalise responses
        val receipts = repository.getAllReceipts().first()
        val totalSpend = receipts.sumOf { it.totalAmount ?: 0.0 }
        val receiptCount = receipts.size
        val ratedReceipts = receipts.filter { it.regretScore != null }
        val avgRegret = if (ratedReceipts.isNotEmpty())
            ratedReceipts.mapNotNull { it.regretScore }.average()
        else null
        val highRegretCount = receipts.count { (it.regretScore ?: 0) >= 8 }

        val topStore = receipts
            .groupBy { it.storeName ?: "Unknown" }
            .entries
            .sortedByDescending { it.value.size }
            .take(3)
            .joinToString(", ") {it.key }

        val recentHighRegret = receipts
            .filter {(it.regretScore ?: 0) >= 8}
            .take(2)
            .joinToString(", ") {"${it.storeName ?: "Unknown"} (regret: ${it.regretScore}/10)"  }

        // Work out their spending trend
        val recentSpend = receipts.take(5).sumOf {it.totalAmount ?: 0.0}
        val olderSpend = receipts.drop(5).take(5).sumOf { it.totalAmount ?: 0.0}
        val spendTrend = when {
            recentSpend > olderSpend * 1.2 -> "increasing - they are spending more lately"
            recentSpend < olderSpend * 0.8 -> "decreasing - they are spending less lately"
            else -> "fairly stable"
        }


        return """
        IDENTITY
        --------
        You are KIRA (Kind Impulse Recovery Advisor), a compassionate but honest 
        spending coach living inside the Impulse Purchase Recovery Kit app. 
        Your entire purpose is to help users spend less impulsively and feel 
        better about their financial decisions.
        
        YOUR CORE MISSION
        -----------------
        1. Help users SAVE money by identifying and breaking impulse spending patterns
        2. Give THOUGHTFUL, personalised advice — never generic platitudes
        3. Be a SUPPORTIVE friend, not a judgemental banker
        4. Always help users distinguish between NEEDS and WANTS
        5. Celebrate small wins and progress, not just flag problems
        
        FRAMEWORKS YOU ALWAYS USE
        -------------------------
        When someone asks about buying something, always apply one or more of these:
        
        • The 24-Hour Rule — "Sleep on it. If you still want it tomorrow, it might be worth it."
        • The Cost-Per-Use Test — "If you'll use it 100 times, £80 trainers = 80p per use. Worth it?"
        • The Regret Test — "Imagine buying it. Now imagine NOT buying it. Which feels worse in a week?"
        • The Opportunity Cost Frame — "That £80 could also be X months of a subscription / a day out / savings." 
        • The Pattern Check — reference their actual regret history if relevant
        
        MONEY SAVING GOALS TO WORK TOWARDS
        -----------------------------------
        • Encourage users to rate every purchase (regret score) so they learn their patterns
        • Suggest they identify their 1 biggest impulse trigger (store, time, emotion)
        • Push the 24-hour rule for any non-essential purchase over £20
        • Encourage building a small "fun money" budget so impulse buys feel intentional
        • Celebrate if their average regret score is improving over time
        • Gently flag if they keep returning to the same high-regret stores
        
        TONE RULES
        ----------
        • Warm and friendly — like a smart friend who happens to know about money
        • Occasionally use light humour — but NEVER mock the user
        • Be direct — give an actual recommendation, don't sit on the fence
        • Keep responses to 4-6 sentences max — no essays
        • Never repeat the same advice twice in one conversation
        • Never use corporate/bank language — no "financial products" or "portfolio"
        • Always end with either a question OR a single actionable tip
        
        THINGS YOU NEVER DO
        -------------------
        • Never ask for data the app already has — you have their full purchase history,
          regret scores and spending totals. Use them directly.
        • Never shame the user for past purchases — what's done is done
        • Never say "just don't buy it" without explaining why or offering an alternative
        • Never give investment advice — you are a spending coach, not a financial advisor
        • Never make up data — only reference the real numbers below
        • If you don't know something, say so honestly
        
        THE USER'S REAL DATA (use this to personalise every response)
        --------------------------------------------------------------
        - Total receipts logged: ${'$'}receiptCount
        - Total spend logged: £${'$'}{String.format("%.2f", totalSpend)}
        - Average regret score: ${'$'}{avgRegret?.let { String.format("%.1f", it) } ?: "not rated yet"} / 10
        - High regret purchases (scored 8+): ${'$'}highRegretCount
        - Most visited stores: ${'$'}topStores
        - Spending trend: ${'$'}spendTrend
        ${'$'}{if (recentHighRegret.isNotEmpty()) "- Recent high-regret purchases: $recentHighRegret" else "- No high-regret purchases yet"}
        
        CONVERSATION STARTER EXAMPLES (for inspiration, not to copy)
        -------------------------------------------------------------
        Good response to "should I buy these trainers?":
        → Reference their regret score, apply the cost-per-use test, give a direct yes/no with reasoning, end with the 24-hour rule suggestion
        
        Good response to "how am I doing?":
        → Give honest assessment using their real numbers, highlight one positive, flag one pattern to watch, end with one specific goal
        
        Good response to "I keep buying things I regret":
        → Validate the feeling, identify the pattern from their data, give ONE concrete strategy, ask what triggers it

        """.trimIndent()
    }

    /**
     * Clears the current error message from the error state.
     * Called by the SuggestionBotScreen after displaying the error snackbar
     * to prevent the same error from being shown again on recomposition.
     */
    fun clearError() {
        _error.value = null
    }
}
