package com.example.impulsepurchaserecoverykit.ui.screens

import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.impulsepurchaserecoverykit.EmotionalResponse

/**
 * Dialog composable that displays a compassionate emotional response when
 * a user logs a high-regret purchase.
 *
 * Shown by the [EmotionalResponseEngine] when a receipt is rated with a
 * regret score at or above the high-regret threshold. The dialog is designed
 * to be supportive rather than judgemental — it acknowledges how the user
 * feels, provides a reassuring message, and offers a practical tip for
 * avoiding a similar situation in the future.
 *
 * The dialog contains three content areas:
 * - A large emoji and headline that set the emotional tone at a glance
 * - A body message that validates the user's feelings and offers encouragement
 * - A tip card with one concrete, actionable suggestion for next time
 *
 * Two actions are offered:
 * - **I'll do better** — dismisses the dialog and returns to the previous screen
 * - **Show my stats** — dismisses the dialog and navigates to the Stats screen
 *   so the user can review their spending and regret patterns in context
 *
 * @param response The [EmotionalResponse] generated by [EmotionalResponseEngine],
 *                 containing the emoji, headline, message, and tip to display
 * @param onDismiss Callback invoked when the user taps "I'll do better" or
 *                  dismisses the dialog by tapping outside it
 * @param onViewStats Callback invoked when the user taps "Show my stats" —
 *                    typically navigates to the Stats screen
 */
@Composable
fun EmotionalResponseDialog(
    response: EmotionalResponse,
    onDismiss: () -> Unit,
    onViewStats: () -> Unit
) {
    AlertDialog(
        onDismissRequest = onDismiss,
        title = {
            // Emoji and headline centred at the top of the dialog
            Column(
                horizontalAlignment = Alignment.CenterHorizontally,
                modifier = Modifier.fillMaxWidth()
            ) {
                Text(
                    text = response.emoji,
                    fontSize = 48.sp,
                    textAlign = TextAlign.Center
                )
                Spacer(Modifier.height(8.dp))
                Text(
                    text = response.headline,
                    style = MaterialTheme.typography.titleLarge,
                    fontWeight = FontWeight.Bold,
                    textAlign = TextAlign.Center
                )
            }
        },
        text = {
            Column(verticalArrangement = Arrangement.spacedBy(12.dp)) {
                // Body message — validates the user's feelings without judgement
                Text(
                    text = response.message,
                    style = MaterialTheme.typography.bodyMedium
                )

                HorizontalDivider()

                // Tip card — one actionable suggestion to help avoid a similar purchase next time
                ElevatedCard(
                    colors = CardDefaults.elevatedCardColors(
                        containerColor = MaterialTheme.colorScheme.secondaryContainer
                    )
                ) {
                    Column(Modifier.padding(12.dp)) {
                        Text(
                            "💡 Tip for next time",
                            style = MaterialTheme.typography.labelLarge,
                            color = MaterialTheme.colorScheme.onSecondaryContainer
                        )
                        Spacer(Modifier.height(4.dp))
                        Text(
                            text = response.tip,
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.onSecondaryContainer
                        )
                    }
                }
            }
        },
        // Primary action — positive framing to encourage the user rather than shame them
        confirmButton = {
            Button(onClick = onDismiss) {
                Text("I'll do better 💪")
            }
        },
        // Secondary action — lets the user immediately review their patterns in context
        dismissButton = {
            OutlinedButton(onClick = onViewStats) {
                Text("Show my stats")
            }
        }
    )
}