package com.example.impulsepurchaserecoverykit.database.entities

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Room database entity representing a single emotion check-in for a receipt.
 *
 * Every time a user completes the Rate Regret screen, a new EmotionEntity is
 * created and stored in the `emotion_checkins` table. It captures the emotional
 * state of the user at the time of rating — including their regret score, their
 * selected mood, and any personal reflection note they chose to add.
 *
 * Each EmotionEntity is linked to a parent [ReceiptEntity] via a foreign key.
 * If the parent receipt is deleted, all associated emotion check-ins are
 * automatically removed from the database via CASCADE deletion, keeping the
 * database free of orphaned records.
 *
 * An index is maintained on [receiptId] to ensure fast lookup of all emotion
 * entries belonging to a specific receipt.
 */
@Entity(
    tableName = "emotion_checkins",
    foreignKeys = [
        ForeignKey(
            entity = ReceiptEntity::class,
            parentColumns = ["id"],
            childColumns = ["receiptId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [Index("receiptId")]
)
data class EmotionEntity(

    /**
     * The unique identifier for this emotion check-in, auto-generated by Room.
     * Defaults to 0 before insertion, after which Room assigns the real ID.
     */
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    /**
     * The ID of the receipt this emotion check-in belongs to.
     * References the [ReceiptEntity.id] column via a foreign key constraint.
     */
    val receiptId: Long,

    /**
     * The timestamp (in milliseconds since epoch) at which the check-in was recorded.
     * Defaults to the current system time at the moment the entity is created.
     */
    val checkInTime: Long = System.currentTimeMillis(),

    /**
     * The user's regret score for this purchase, on a scale of 1 to 10.
     * 1 indicates no regret at all; 10 indicates maximum regret.
     * Set by the slider on the Rate Regret screen.
     */
    val regretScore: Int,

    /**
     * The user's selected mood at the time of rating.
     * Possible values: "regretful", "neutral", "satisfied".
     * Captured from the mood chip selection on the Rate Regret screen.
     */
    val mood: String,

    /**
     * An optional personal reflection note added by the user.
     * Captured from the free-text field on the Rate Regret screen.
     * Null if the user chose not to add a note.
     */
    val notes: String?
)