package com.example.impulsepurchaserecoverykit.database.entities

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Room database entity representing a single line item parsed from a receipt.
 *
 * When a receipt is scanned and parsed by Claude AI, each individual product
 * or service on the receipt is stored as a separate ItemEntity in the `items`
 * table. This allows the app to display a full itemised breakdown on the
 * Receipt Detail screen and enables per-item sentiment reactions through
 * [ItemReactionEntity].
 *
 * Each ItemEntity belongs to a parent [ReceiptEntity] via a foreign key.
 * If the parent receipt is deleted, all of its associated items are
 * automatically removed via CASCADE deletion, ensuring no orphaned item
 * records remain in the database.
 *
 * An index is maintained on [receiptId] to ensure efficient retrieval
 * of all items belonging to a specific receipt.
 */
@Entity(
    tableName = "items",
    foreignKeys = [
        ForeignKey(
            entity = ReceiptEntity::class,
            parentColumns = ["id"],
            childColumns = ["receiptId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [Index("receiptId")]
)
data class ItemEntity(

    /**
     * The unique identifier for this item, auto-generated by Room.
     * Defaults to 0 before insertion, after which Room assigns the real ID.
     */
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    /**
     * The ID of the receipt this item belongs to.
     * References the [ReceiptEntity.id] column via a foreign key constraint.
     */
    val receiptId: Long,

    /**
     * The name of the item as extracted from the receipt by ML Kit OCR
     * and parsed by Claude AI. For example "Relaxed Fit Hoodie" or "Flat White".
     */
    val name: String,

    /**
     * The price of a single unit of this item in GBP.
     * Parsed from the receipt total and divided by [quantity] where applicable.
     */
    val price: Double,

    /**
     * The number of units of this item purchased.
     * Defaults to 1 if the receipt does not specify a quantity.
     */
    val quantity: Int = 1,

    /**
     * The spending category assigned to this item.
     * Used to group items on the Category Stats screen.
     * Defaults to "other" if Claude AI cannot determine a category.
     * Example values: "tops", "beverage", "accessories", "bottoms".
     */
    val category: String = "other"
)